# Generated by Django 3.2.10 on 2022-04-12 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('ID', models.UUIDField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_type', models.CharField(max_length=55)),
                ('post_category', models.CharField(max_length=55)),
                ('post_status', models.CharField(max_length=55)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogMedia',
            fields=[
                ('ID', models.UUIDField(primary_key=True, serialize=False)),
                ('media_name', models.CharField(max_length=80)),
                ('media_path', models.TextField()),
                ('media_type', models.CharField(max_length=20)),
                ('media_status', models.CharField(max_length=20)),
                ('media_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('editor_name', models.TextField()),
                ('media_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('media_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
        ),
    ]
