# Generated by Django 3.2.10 on 2022-04-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220417_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmedia',
            name='media_category',
            field=models.TextField(max_length=40),
        ),
    ]
